version: '2'
services:
      auditii_db:
            image: postgres:9.4.7
            container_name: auditii-db
            ports:
                  - "5432"
            environment:
                  - POSTGRES_USER=odoo
                  - POSTGRES_PASSWORD=odoo
      auditii:
            image: odoo:9
            container_name: auditii
            volumes:
                  - ./src:/mnt/extra-addons
            ports:
                  - "9089:8069"
            environment:
                  - DB_PORT_5432_TCP_ADDR=auditii_db
                  - DB_PORT_5432_TCP_PORT=5432
                  - DB_ENV_POSTGRES_USER=odoo
                  - DB_ENV_POSTGRES_PASSWORD=odoo
            depends_on:
                  - auditii_db
